### ISSUE TITLE
Solution exception and no params.json or static.json output

### ISSUE THREAD

**Issue by XiaomingY** [didimitrie/speckle.exporter#10]
Hi,

Just compiled the exported and trying to get it to work. This is what I found:
(1) after exporting **,**,**,.json, there is a solution exception, params.json and static.json are not exported.
(2) Once the grasshopper file with the Beta.Speckle closed, I cannot open it anymore. An error occurs.(Object reference not set to an instance of an object)

Could you upload an gha file and perhaps a sample grasshopper file that we could test with?
Thank you.

Xiaoming

**Comment by didimitrie** [comment]
This might be because through your iterations you're encountering a null object.
Here's a defintion you can try it out with (unzip, there's the json files and **def.ghx** which is what you're looking for): 
[CylinderTest.zip](https://github.com/didimitrie/speckle.exporter/files/238371/CylinderTest.zip)

Can you also send over the def that's causing problems? I can look into it and see where the fuckup happens...

**Comment by XiaomingY** [comment]
Hi Dimitrie,

Thank you for the sample file. I can use the def.ghx in the zip and regenerate the package. The definition I have is as [attached](https://onedrive.live.com/redir?resid=D4240A8D45208577!125&authkey=!APr9RUzroxYUsrU&ithint=file%2cghx). Two sliders are connected to SLD, volume output to PRF. Scaled mesh box connected to OBJ and unscaled box connected to STA. Once I connect everything to Speckle, I cannot reopen the grasshopper file anymore.

Xiaoming

**Comment by didimitrie** [comment]
## will look at it asap - sounds quite strange :)

dimitrie.org http://dimitrie.org/
@idid https://twitter.com/idid

**Comment by didimitrie** [comment]
Found the problem: 
I'm afraid any performance measure needs to be coming from a named panel, not directly from a component. It's something I'm planning to support in the future, but for now **you must pass all performance measures through a panel** before connecting them to speckle. 

Here's the model online:
http://beta.speckle.xyz/view/s/4JyN0TKxb
Screenshot:
![canvas at 16 49 26](https://cloud.githubusercontent.com/assets/7696515/14858466/18c5b634-0c98-11e6-8ca9-47114296ee78.png)
