### ISSUE TITLE
Export path

### ISSUE THREAD

**Issue by max-malein** [didimitrie/speckle.exporter#3]
I have an issue with saving path in the component.
_`1. Solution exception:Отказано в доступе по пути "C:\Users\\Documents\Speckle Models\02.Beta.Speckle.MoreComplexExample`"._

Those non-Latin characters basically say "access denied". And there's also 'user' missing in the path most likely because it's in Cyrillic.

It would be great to have an option to provide a custom path for exporting. I believe that would solve the issue.

**Comment by didimitrie** [comment]
I've been considering that - it's going to be there in the next iteration. I am definitively not going to start debugging windows permission stuff :)

**Comment by didimitrie** [comment]
added in 385004102dff7736bf6d9aabaadef7a7d3450c1b
