### ISSUE TITLE
Compiling error at line 568 BetaSpeckleComponent.cs

### ISSUE THREAD

**Issue by XiaomingY** [didimitrie/speckle.exporter#5]
HI,

I tried to build the solution with visual studio express 2013. Error occurs at line 568 BetaSpeckleComponent.cs. "Error 1   Cannot apply indexing with [] to an expression of type 'Grasshopper.Kernel.Data.IGH_StructureEnumerator'. Any idea about it? Thank you.

**Comment by didimitrie** [comment]
Ah, damns. Yep, it's wrong. Replace 
`myParam.VolatileData.AllData(true)[0];`
with
`myParam.VolatileData.AllData(true).ToString();`
and do a pull request :) 

This is a fix from the top of my head, I will look into the issue later on. Let me know how it goes!

**Comment by didimitrie** [comment]
@bilinxing9 ignore previous comment, it should be fixed now!
